Use meson's install_subdir instead of naming data files individually
libratbag/libratbag pull request #1242
Opened 2021-12-10 04:40 UTC by whot

I can't remember why we didn't do this in the first place but not requiring every `.device` file to be listed in `meson.build` seems like a win.

2021-12-10 09:25 UTC, perigoso commented
makes sense to me

2021-12-10 09:29 UTC, perigoso approved these changes

2021-12-10 09:35 UTC, perigoso requested changes
maybe bump the meson required version? seemingly we are using features that require 0.50, but we only state 0.40 as required, this PR also requires >= 0.42

```
WARNING: Project specifies a minimum meson_version '>= 0.40.0' but uses features which were added in newer versions:
 * 0.42.0: {'exclude_files arg in install_subdir'}
 * 0.46.0: {'Python Module'}
 * 0.50.0: {'install arg in configure_file'}
```

2021-12-12 23:05 UTC, amfern approved these changes

2021-12-12 23:43 UTC, whot commented
> maybe bump the meson required version? 

Done in #1245 now, we can merge that one first and rebase this one so the history is pretty

2021-12-12 23:55 UTC, perigoso approved these changes

2021-12-13 00:39 UTC, merged