Added device: Logitech MX Master 3s
libratbag/libratbag pull request #1346
Opened 2022-09-17 13:30 UTC by NL-TCH

Tested and working with all buttons, dpi etc..

output of sudo ratbagd --verbose:
```
Initializing libratbag
ratbag debug: New device: SYNA7DB5:01 06CB:7DB7
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 06cb:7db7
ratbag debug: New device: MX Master 3S
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x05 vendor 0x46d product 0xffffb034
ratbag debug: MX Master 3S is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports long reports

ratbag raw: hidpp write:  xxxx
ratbag raw: hidpp read:  xxxx

ratbag debug: 'MX Master 3S' is using protocol v4.5
ratbag raw: 'MX Master 3S' has 36 features
ratbag raw: Init feature HIDPP_PAGE_ROOT (0x0000) 
ratbag raw: hidpp write:  11 02 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0000 is at 0x00
ratbag raw: Init feature HIDPP_PAGE_FEATURE_SET (0x0001) 
ratbag raw: hidpp write:  11 02 00 08 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: Init feature HIDPP_PAGE_DEVICE_INFO (0x0003) 
ratbag raw: hidpp write:  11 02 00 08 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 02 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0003 is at 0x02
ratbag raw: unknown feature 0x0003
ratbag raw: Init feature HIDPP_PAGE_DEVICE_NAME (0x0005) 
ratbag raw: hidpp write:  11 02 00 08 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0005 is at 0x03
ratbag raw: unknown feature 0x0005
ratbag raw: Init feature HIDPP_PAGE_WIRELESS_DEVICE_STATUS (0x1d4b) 
ratbag raw: hidpp write:  11 02 00 08 1d 4b 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1d4b is at 0x04
ratbag raw: unknown feature 0x1d4b
ratbag raw: Init feature HIDPP_PAGE_RESET (0x0020) 
ratbag raw: hidpp write:  11 02 00 08 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0020 is at 0x05
ratbag raw: unknown feature 0x0020
ratbag raw: Init feature 0x21 (0x0021) 
ratbag raw: hidpp write:  11 02 00 08 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 06 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0021 is at 0x06
ratbag raw: unknown feature 0x0021
ratbag raw: Init feature  0x7 (0x0007) 
ratbag raw: hidpp write:  11 02 00 08 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0007 is at 0x07
ratbag raw: unknown feature 0x0007
ratbag raw: Init feature 0x1004 (0x1004) 
ratbag raw: hidpp write:  11 02 00 08 10 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 08 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1004 is at 0x08
ratbag raw: unknown feature 0x1004
ratbag raw: Init feature HIDPP_PAGE_SPECIAL_KEYS_BUTTONS (0x1b04) 
ratbag raw: hidpp write:  11 02 00 08 1b 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 00 08 09 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1b04 is at 0x09
ratbag debug: device has programmable keys/buttons
ratbag raw: hidpp write:  11 02 09 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 08 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: device has 8 buttons
ratbag raw: hidpp write:  11 02 09 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 50 00 38 01 00 01 01 04 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 0: cid: 'Left' (80) tid: 'Left Click' (56) flags: 0x01 pos: 0 group: 1 gmask: 0x01 raw_XY: no
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 51 00 39 01 00 01 01 04 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 51 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 51 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 1: cid: 'Right' (81) tid: 'Right Click' (57) flags: 0x01 pos: 0 group: 1 gmask: 0x01 raw_XY: no
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 52 00 3a 31 00 02 03 05 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 52 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 52 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 2: cid: 'Middle' (82) tid: 'Middle Click' (58) flags: 0x31 pos: 0 group: 2 gmask: 0x03 raw_XY: yes
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 53 00 3c 31 00 02 03 05 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 53 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 53 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 3: cid: 'Back' (83) tid: 'Back Click' (60) flags: 0x31 pos: 0 group: 2 gmask: 0x03 raw_XY: yes
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 56 00 3e 31 00 02 03 05 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 56 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 56 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 4: cid: 'Forward' (86) tid: 'Forward Click' (62) flags: 0x31 pos: 0 group: 2 gmask: 0x03 raw_XY: yes
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 c3 00 a9 31 00 02 03 05 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 c3 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 c3 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 5: cid: 'AppSwitchGesture' (195) tid: 'Gesture Button' (169) flags: 0x31 pos: 0 group: 2 gmask: 0x03 raw_XY: yes
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 c4 00 9d 31 00 02 03 05 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28 00 c4 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 28 00 c4 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: control 6: cid: 'SmartShift' (196) tid: 'SmartShift' (157) flags: 0x31 pos: 0 group: 2 gmask: 0x03 raw_XY: yes
      reporting: raw_xy: no persist: no divert: no remapped: 'None' (0)
ratbag raw: hidpp write:  11 02 09 18 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 02 09 18 00 d7 00 b4 a0 00 03 00 03 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 02 09 28  [...]

2022-10-01 12:21 UTC, NixonNelson22 approved these changes

2022-10-02 15:05 UTC, staticssleever668 requested changes
If possible, could you also squash all of the commits into a single one?

2022-10-02 15:05 UTC, staticssleever668 commented on data/devices/logitech-MX-Master-3s.device
> +DeviceMatch=bluetooth:046d:b034;usb:046d:c548
```suggestion
DeviceMatch=bluetooth:046d:b034
```
Please, remove the receiver ID `usb:046d:c548`. It is not specific to this device, so it does not fit in this device file. :)

2022-10-02 15:05 UTC, staticssleever668 commented on data/devices/logitech-MX-Master-3s.device
> +# Logitech MX Master 3S
Redundant comment.
```suggestion
```

2022-10-31 22:41 UTC, closed without merging

2022-10-31 22:48 UTC, staticssleever668 commented
God, so this is why some repos don't accept pull requests from the `master` branch - GitHub doesn't let me push *new* commits there, but it let me update your branch to the upstream's `master`, which for some reason also closed the PR automatically.
@NL-TCH, would you please make a new branch and make the same pull request from there?
Locally you would have to clone your repository, then just do `git switch --create feat_logitech_mx_master_3s` and `git push`.

2022-11-16 23:44 UTC, whot commented
@staticssleever668 fwiw, I've bumped you up to maintainer now, in case that helps next time. Also, there's [this action](https://github.com/marketplace/actions/github-repo-branch-naming-policy-action) which may let us prevent merges from forked `master` branches (haven't tried it though).

2022-12-11 17:38 UTC, kodein1 commented
Hi nltech, could you reopen the request to add mx3s for staticssleever668?

2022-12-11 21:24 UTC, staticssleever668 commented
@kodein1 
I remade the pull request myself in #1382, however we will now have to wait until another maintainer approves it.

2022-12-11 22:44 UTC, whot commented
> however we will now have to wait until another maintainer approves it.

@staticssleever668: I'm pretty sure you have the permissions to merge anyway, right? For things like that, waiting for two reviews is a bit pointless, let alone our lack of reviewers... anyway, I found that checkbox and unticked it, formal review approval is no longer required.

2024-05-08 08:39 UTC, hex20dec commented
Hi all, no matter what I‌ try, I‌ am unable to get it to work on my machine.
I am using the bolt receiver.
Here is my output:
```
ratbag debug: No data file found for 046d:4023
ratbag debug: New device: Logitech Wireless Mouse PID:4038
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: No data file found for 046d:4038
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
ratbag debug: New device: Logitech USB Receiver
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: 046d:c548 is a Logitech receiver, not a device. Ignoring...
DBus server ready
```

So I‌ added ``` usb:046d:4038 ``` to the data file, and now I‌ am getting this error:

```
ratbag debug: New device: Logitech Wireless Mouse PID:4038
ratbag debug: Using data directory '/usr/local/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc534
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4023
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0x4038
ratbag debug: Logitech Wireless Mouse PID:4038 is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 20
ratbag debug: - HID report ID 21
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   10 02 8f 00 18 09 00
ratbag debug:     HID++ error from the device (2): ERR_UNSUPPORTED (09)
...
```

Is it even suppose to work with the bolt receiver or only with bluetooth?