Minor ASUS driver refactoring
libratbag/libratbag pull request #1381
Opened 2022-12-09 15:19 UTC by staticssleever668

To fix a compiler warning:
```
[60/72] Compiling C object libratbag.a.p/src_libratbag-data.c.o
In file included from ../src/libratbag-data.c:33:
../src/asus.h:138:27: warning: ‘ASUS_BUTTON_MAPPING’ defined but not used [-Wunused-variable]
  138 | static struct asus_button ASUS_BUTTON_MAPPING[] = {
      |                           ^~~~~~~~~~~~~~~~~~~
```

2022-12-09 15:20 UTC, staticssleever668 commented
@kyokenn could you take a look at this?
I don't have an ASUS mouse to test this.

2022-12-09 16:13 UTC, kyokenn requested changes

2022-12-21 10:33 UTC, kyokenn commented
Looks good.

2022-12-21 11:19 UTC, merged

2022-12-21 11:19 UTC, staticssleever668 commented
Thanks for reviewing!