asus: check for hid report and fix chakram x
libratbag/libratbag pull request #1468
Opened 2023-03-30 06:47 UTC by kyokenn

Fixes https://github.com/libratbag/libratbag/issues/1413

Every ASUS mouse have multiple interfaces for mouse, keyboard, configuration and other stuff. There was some error messages because libratbag tried to initialize on the wrong interfaces of the mouse. It tries every interface and fails on the wrong one with error message. This PR fixes it and I have tested this part.

2023-03-30 20:56 UTC, staticssleever668 requested changes
One little change and it's good (you could also split this into two commits but whatever). Thank you so much for your work on the asus driver! :)

2023-03-30 20:56 UTC, staticssleever668 commented on src/driver-asus.c
> +		return -1;
Could you change this to `-ENODEV`?
The `probe` function is supposed to only return POSIX error codes on error, moreover, if it's something other than ENODEV it's going to print it to stderr.

2023-03-31 07:01 UTC, kyokenn commented
"ratbag_hidraw_has_report" doesn't work for me anymore for some reason. Maybe I have updated some packages. So I replaced it with profile request, it should work even when the mouse is sleeping or turned off.

2023-03-31 11:13 UTC, staticssleever668 approved these changes

2023-03-31 11:17 UTC, merged

2023-03-31 11:23 UTC, staticssleever668 commented
> "ratbag_hidraw_has_report" doesn't work for me anymore for some reason.
Well, if you find a way to use it instead, feel free to open another PR to avoid duplicate work.